# Generated by Django 4.0.2 on 2022-02-18 17:23

from django.db import migrations
import routes4life_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("routes4life_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", routes4life_api.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
