# Generated by Django 4.0.3 on 2022-05-20 23:18

from django.db import migrations, models
import routes4life_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('routes4life_api', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=routes4life_api.utils.upload_avatar_to),
        ),
    ]
