# Generated by Django 4.0.3 on 2022-06-03 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes4life_api', '0008_place_placeimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
        migrations.CreateModel(
            name='PlaceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes4life_api.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
