# Generated by Django 4.0.3 on 2022-06-06 08:22

from django.db import migrations, models
import django.db.models.deletion
import routes4life_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('routes4life_api', '0009_remove_place_rating_placerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=routes4life_api.utils.upload_place_mainimg_to),
        ),
        migrations.AlterField(
            model_name='placerating',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='routes4life_api.place'),
        ),
    ]
