# Generated by Django 4.0.3 on 2022-06-13 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes4life_api', '0011_alter_placeimages_image_alter_placeimages_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
    ]
