# Generated by Django 4.0.3 on 2022-06-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes4life_api', '0013_remove_place_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='places',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='routes4life_api.place'),
        ),
    ]
