# Generated by Django 4.0.3 on 2022-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes4life_api', '0015_rename_placeimages_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(default='Other', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
